$ speedtest
Retrieving speedtest.net configuration...
Testing from Deutsche Telekom AG (217.85.188.208)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by 31173 Services AB (Frankfurt) [70.04 km]: 20.952 ms
Testing download speed................................................................................
Download: 12.05 Mbit/s
Testing upload speed..................................................................................
Upload: 2.99 Mbit/s
